apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: gameon-system
  labels:
    app: gameon-auth
spec:
  type: ClusterIP
  ports:
  - port: 9080
    name: http
  selector:
    app: gameon-auth
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: auth-deploy
  namespace: gameon-system
  labels:
    app: gameon-auth
spec:
  template:
    metadata:
      labels:
        app: gameon-auth
    spec:
      volumes:
      - name: certificate
        secret:
          secretName: global-cert
      containers:
      - name: auth
        image: gameontext/gameon-auth:lastgood
        imagePullPolicy: IfNotPresent
        ports:
        - name: auth
          containerPort: 9080
        readinessProbe:
          httpGet:
            path: /auth/health
            port: 9080
          initialDelaySeconds: 40
        volumeMounts:
        - name: certificate
          mountPath: /etc/cert
        envFrom:
        - configMapRef:
            name: global-config
