apiVersion: v1
kind: Service
metadata:
  name: mediator
  namespace: gameon-system
  labels:
    app: gameon-mediator
spec:
  type: ClusterIP
  ports:
  - port: 9080
    name: http
  selector:
    app: gameon-mediator
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mediator-deploy
  namespace: gameon-system
  labels:
    app: gameon-mediator
spec:
  template:
    metadata:
      labels:
        app: gameon-mediator
      annotations:
        traffic.sidecar.istio.io/includeOutboundIPRanges: 10.0.0.1/24
    spec:
      volumes:
      - name: certificate
        secret:
          secretName: global-cert
      containers:
      - name: mediator
        image: gameontext/gameon-mediator:lastgood
        imagePullPolicy: IfNotPresent
        ports:
        - name: mediator
          containerPort: 9080
        readinessProbe:
          httpGet:
            path: /mediator/
            port: 9080
          initialDelaySeconds: 40
        volumeMounts:
        - name: certificate
          mountPath: /etc/cert
        envFrom:
        - configMapRef:
            name: global-config
