apiVersion: v1
kind: Service
metadata:
  name: player
  namespace: gameon-system
  labels:
    app: gameon-player
spec:
  type: ClusterIP
  ports:
  - port: 9080
    name: http
  selector:
    app: gameon-player
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: player
  namespace: gameon-system
  labels:
    app: gameon-player
spec:
  template:
    metadata:
      labels:
        app: gameon-player
    spec:
      volumes:
      - name: certificate
        secret:
          secretName: global-cert
      containers:
      - image: gameontext/gameon-player:lastgood
        imagePullPolicy: Always
        name: player
        ports:
        - containerPort: 9080
          name: player
        readinessProbe:
          httpGet:
            path: /players/v1/health
            port: 9080
          initialDelaySeconds: 40
        volumeMounts:
        - name: certificate
          mountPath: /etc/cert
        envFrom:
        - configMapRef:
            name: global-config
